name: Apply Terraform Configuration

on:
  workflow_dispatch:
    inputs:
        working-directory:
            required: true
            type: string
#   schedule:
#     # Every day from Monday to Friday at 03:30 AM UTC
#     - cron: '30 3 * * 1-5'

jobs:
    terraform:
        # runs-on: [self-hosted, uniqueString]
        runs-on: ubuntu-22.04
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
          
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
         
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            
          - name: Terraform Init
            run: terraform init
            working-directory: ${{ inputs.terraform-module }}
          
          - name: Terraform Validate
            run: terraform validate -no-color
            working-directory: ${{ inputs.terraform-module }}
          
        #   - name: Terraform Workspace
        #     run: terraform workspace select ${{ inputs.terraform-workspace }}
        #     working-directory: ${{ inputs.terraform-module }}
          
          - name: Apply Terraform Configuration
            run: terraform apply -auto-approve -no-color
            working-directory: ${{ inputs.terraform-module }}